name: Smart Home UI Manager
description: Instala y administra componentes personalizados para Home Assistant
version: "0.1.7"
slug: ui_manager
init: false

arch:
  - aarch64
  - amd64

startup: application
boot: auto

stage: experimental

homeassistant_api: true

map:
  - type: homeassistant_config
    read_only: false
    path: /config
